// ##############################
//			  acpi.h
// ##############################

#ifndef _ACPI_AML_H_
#define _ACPI_AML_H_

#define AML_ZERO_OP                 0x00
#define AML_ONE_OP                  0x01
#define AML_ALIAS_OP                0x06
#define AML_NAME_OP                 0x08
#define AML_BYTE_PREFIX             0x0A
#define AML_WORD_PREFIX             0x0B
#define AML_DWORD_PREFIX            0x0C
#define AML_STRING_PREFIX           0x0D
#define AML_QWORD_PREFIX            0x0E
#define AML_SCOPE_OP                0x10
#define AML_BUFFER_OP               0x11
#define AML_PACKAGE_OP              0x12
#define AML_VAR_PACKAGE_OP          0x13
#define AML_METHOD_OP               0x14
#define AML_EXTERNAL_OP             0x15
#define AML_DUAL_NAME__PREFIX       0x2E
#define AML_MULTI_NAME_PREFIX       0x2F
#define AML_DIGIT_CHAR              0x00
#define AML_NAME_CHAR               0x00
#define AML_EXT_OP_PREFIX           0x5B
#define AML_MUTEX_OP                0x5B01
#define AML_EVENT_OP                0x5B02
#define AML_COND_REF_OF_OP          0x5B12	
#define AML_CREATE_FIELD_OP         0x5B13	
#define AML_LOAD_TABLE_OP           0x5B1F	
#define AML_LOAD_OP                 0x5B20
#define AML_STALL_OP                0x5B21
#define AML_SLEEP_OP                0x5B22
#define AML_ACQUIRE_OP              0x5B23
#define AML_SIGNAL_OP               0x5B24
#define AML_WAIT_OP                 0x5B25
#define AML_RESET_OP                0x5B26
#define AML_RELEASE_OP              0x5B27
#define AML_FROM_BCD_OP             0x5B28
#define AML_TO_BCD                  0x5B29
#define AML_RESERVED                0x5B2A
#define AML_REVISION_OP             0x5B30
#define AML_DEBUG_OP                0x5B31
#define AML_FATAL_OP                0x5B32
#define AML_TIMER_OP                0x5B33
#define AML_OP_REGION_OP            0x5B80
#define AML_FIELD_OP                0x5B81
#define AML_DEVICE_OP               0x5B82
#define AML_PROCESSOR_OP            0x5B83
#define AML_POWER_RES_OP			0x5B84
#define AML_THERMAL_ZONE_OP         0x5B85
#define AML_INDEX_FIELD_OP          0x5B86
#define AML_BANK_FIELD_OP           0x5B87
#define AML_DATA_REGION_OP          0x5B88
#define AML_ROOT_CHAR               0x5C
#define AML_PARENT_PREFIX_CHAR      0x5E
#define AML_NAME_CHARB              0x5F
#define AML_LOCAL0_OP               0x60
#define AML_LOCAL1_OP               0x61
#define AML_LOCAL2_OP               0x62
#define AML_LOCAL3_OP               0x63
#define AML_LOCAL4_OP               0x64
#define AML_LOCAL5_OP               0x65
#define AML_LOCAL6_OP               0x66
#define AML_LOCAL7_OP               0x67
#define AML_ARG0_OP                 0x68
#define AML_ARG1_OP                 0x69
#define AML_ARG2_OP                 0x6A
#define AML_ARG3_OP                 0x6B
#define AML_ARG4_OP                 0x6C
#define AML_ARG5_OP                 0x6D
#define AML_ARG6_OP                 0x6E
#define AML_STORE_OP                0x70
#define AML_REF_OF_OP               0x71
#define AML_ADD_OP                  0x72
#define AML_CONCAT_OP               0x73
#define AML_SUBTRACT_OP             0x74
#define AML_INCREMENT_OP            0x75
#define AML_DECREMENT_OP            0x76
#define AML_MULTIPLY_OP             0x77
#define AML_DIVIDE_OP               0x78
#define AML_SHIFT_LEFT_OP           0x79
#define AML_SHIFT_RIGHT_OP          0x7A
#define AML_AND_OP                  0x7B
#define AML_NAND_OP                 0x7C
#define AML_OR_OP                   0x7D
#define AML_NOR_OP                  0x7E
#define AML_XOR_OP                  0x7F
#define AML_NOT_OP                  0x80
#define AML_FIND_SET_LEFT_BIT_OP    0x81
#define AML_FIND_SET_RIGHT_BIT_OP   0x82
#define AML_DEREF_OF_OP             0x83
#define AML_CONCAT_RES_OP           0x84
#define AML_MOD_OP                  0x85
#define AML_NOTIFY_OP               0x86
#define AML_SIZE_OF_OP              0x87
#define AML_INDEX_OF_OP             0x88
#define AML_MATCH_OP                0x89
#define AML_CREATE_DWORD_FIELD_OP   0x8A
#define AML_CREATE_WORD_FIELD_OP    0x8B
#define AML_CREATE_BYTE_FIELD_OP    0x8C
#define AML_CREATE_BIT_FIELD_OP     0x8D
#define AML_OBJECT_TYPE_OP          0x8E
#define AML_CREATE_QWORD_FIELD_OP   0x8F
#define AML_L_AND_OP                0x90
#define AML_L_OR_OP                 0x91
#define AML_L_NOT_OP                0x92
#define AML_L_NOT_EQUAL_OP          0x9293
#define AML_L_LESS_EQIAL_OP         0x9294
#define AML_L_GREATER_EQUAL_OP      0x9295
#define AML_LEQUAL_OP               0x93
#define AML_LGREATER_OP             0x94
#define AML_L_LESS_OP               0x95
#define AML_L_BUFFER_OP             0x96
#define AML_TO_DECIMAL_STRING_OP    0x97
#define AML_TO_HEX_STRING_OP        0x98
#define AML_TO_INTEGER_OP           0x99
#define AML_TO_STING_OP             0x9C
#define AML_COPY_OBJECT_OP          0x9D
#define AML_MID_OP                  0x9E
#define AML_CONTINUE_OP             0x9F
#define AML_IF_OP                   0xA0
#define AML_ELSE_OP                 0xA1
#define AML_WJILE_OP                0xA2
#define AML_NOOP_OP                 0xA3
#define AML_RETURN_OP               0xA4
#define AML_BREAK_OP                0xA5
#define AML_BREAK_POINT_OP          0xCC
#define AML_ONES_OP                 0xFF

#endif